services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  service1:
    build: ./service_1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  service2:
    build: ./service_2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s